// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lprabkfxfatolrgmtsao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwcmFia2Z4ZmF0b2xyZ210c2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mjc1NzYsImV4cCI6MjA2OTMwMzU3Nn0.Q1elBPQNS4GQQ-bZEnrqVb-oI-NVD03RKlw_dty56PI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});